### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by eakteam** [franmontiel/LocaleChanger#6] opened 2017-12-28 16:53 UTC
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2981)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3042)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1639)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6780)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)
Caused by: java.lang.NullPointerException: 
  at com.franmontiel.localechanger.LocaleChanger.configureBaseContext (LocaleChanger.java:119)
  at com.eakteam.networkmanager.paneli_kryesor.attachBaseContext (paneli_kryesor.java:201)
  at android.app.Activity.attach (Activity.java:6884)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2894)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3042)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1639)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6780)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)
```

MAIN APP

```
public class MainApplication extends Application {

    public static final List<Locale> SUPPORTED_LOCALES =
            Arrays.asList(
                    new Locale("en", "US"),
                    new Locale("sq", "AL")
            );

    @Override
    public void onCreate() {
        super.onCreate();
        LocaleChanger.initialize(getApplicationContext(), SUPPORTED_LOCALES);
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        LocaleChanger.onConfigurationChanged();
    }
}
```

MAIN ACTIVITY 
```

@Override
    protected void attachBaseContext(Context newBase) {
        newBase = LocaleChanger.configureBaseContext(newBase);
        super.attachBaseContext(newBase);
    }
```

I'm using Crashlytics from Fabric too if this is needed to know ....

**Comment by MohdShamim111** [comment] 2018-02-03 05:31
Ok

**Comment by eakteam** [comment] 2018-06-24 14:12
Any idea how to solve it ?

**Comment by franmontiel** [comment] 2018-11-15 18:09
For what I see your code seems to be fine. 
It can be possible that you are not declaring your MainApplication in the Manifest and that way LocaleChanger.initialize is not executed?

**Comment by eakteam** [comment] 2018-11-15 18:11
The manifest is fine, i have checked it. But anyway will be there any update to this lib in following ?

**Comment by franmontiel** [comment] 2018-11-15 18:37
It will have minor updates when needed.

I have not much time to track your issue but if you can help me providing more info about your problem I might be able to detect the problem and release a fix.

* It is an issue that is preventing you from using the library or you already have published and you find this problem in some deviceS?

* If you have time to download the source code and debug what is happening to you (I suppose that the inner delegate is null but I am not sure looking at your stack trace).

**Comment by rishabh-smartlinks** [comment] 2019-10-18 11:47
same issue with me.

**Comment by franmontiel** [comment] 2020-12-28 01:39
It has been impossible for me to reproduce this issue. 
Maybe it is related with this report? https://github.com/franmontiel/LocaleChanger/issues/3
Closing it until more information is available

**Closed as completed by franmontiel** 2020-12-28 01:39 UTC
